### ISSUE TITLE
How to get a Hyperbolic Uncertainty map?

### ISSUE THREAD

**Issue by shuaige-inthewind** [MinaGhadimiAtigh/HyperbolicImageSegmentation#1]
How do I get the Hyperbolic Uncertainty map of a picture？

**Comment by MinaGhadimiAtigh** [comment]
The code in **generate_confidence_map.py** is to generate the _confidence map_ (with has an inverse relation with uncertainty) given input image. 

First, you should train a segmentation model. Then, the code will load the model and generate and show the confidence map.
