### ISSUE TITLE
'. record' file not found

### ISSUE THREAD

**Issue by 17762516420** [MinaGhadimiAtigh/HyperbolicImageSegmentation#4]
Hi! Thanks for sharing the code!
I tried to reproduce this work but had some trouble finding 'coco_train.record' and 'coco_val.record'.
Will these files be shared? Or shall I download them from elsewhere?
Thank you!

**Comment by MinaGhadimiAtigh** [comment]
Hi, sorry for the late reply. 
I've uploaded the data files to Google Drive. You can download it here.

https://drive.google.com/drive/folders/1AggSC8fKCgRsfYjTjVRjoOfa85g2KBBu?usp=sharing

If you want to know the details on creating the record files, let me know.
